# -*- coding: utf-8 -*-
"""Data Science projects

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W_ZY5JPKdvScyzkfue4MOHeplI2UgOyP
"""

# Install Required Libraries
!pip install pandas matplotlib seaborn

## Import Libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Load the Dataset
df = pd.read_csv("/content/netflix_titles.csv")

df.head()

## Check Dataset Information
df.info()
df.describe()

## Check Missing Values
df.isnull().sum()

## Movies vs TV Shows Count
sns.countplot(x='type', data=df)
plt.title("Movies vs TV Shows on Netflix")
plt.show()

## Top 10 Countries Producing Netflix Content
top_countries = df['country'].value_counts().head(10)

top_countries.plot(kind='bar')
plt.title("Top 10 Countries Producing Netflix Content")
plt.xlabel("Country")
plt.ylabel("Number of Titles")
plt.show()

## Content Added Per Year
df['release_year'].value_counts().sort_index().plot()

plt.title("Netflix Content Released Per Year")
plt.xlabel("Year")
plt.ylabel("Number of Shows")
plt.show()

## Most Popular Genres
genres = df['listed_in'].str.split(',', expand=True).stack()

top_genres = genres.value_counts().head(10)

top_genres.plot(kind='bar')

plt.title("Top 10 Netflix Genres")
plt.show()

## Ratings Distribution
sns.countplot(y='rating', data=df, order=df['rating'].value_counts().index)

plt.title("Distribution of Ratings on Netflix")
plt.show()